description: >
  The default executor is the CircleCI Python Image
docker:
  - image: 'cimg/python:<<parameters.tag>>'
parameters:
  tag:
    default: "3.8"
    description: >
      Pyhton version to use to run Permifrost.
      https://hub.docker.com/r/cimg/python/tags
    type: string
